### ISSUE TITLE
Does not support the port in the image name

### ISSUE THREAD

**Issue by corey-aloia-sap** [Microsoft/vscode-docker#280]
if you write a from like this:

FROM repository.mycompany:5000/tomcat:8.0

then there will be an error "invalid reference format", with the 8.0 being underlined in red, although this is a valid statement.

**Comment by rcjsuen** [comment]
Hi, @corey-aloia-sap. Thank you for your bug report.

It sounds very similar to #269 although your image is simply `tomcat:8.0` and not something like `apache/tomcat:8.0`. It should still be fixed by rcjsuen/dockerfile-utils#39 though as I have a test for something very similar to what you have provided.

https://github.com/rcjsuen/dockerfile-utils/blob/4975fe383f809c16f944d6aec41aa87c6294a584/test/dockerValidator.test.ts#L2672-L2673

**Comment by corey-aloia-sap** [comment]
yep, sorry about that! I could have looked through the open bugs a bit harder. Looks like the same issue.

**Comment by lucianenache** [comment]
Hi, I didn't knew which issue to use between #269 and #280 so I have picked the later one. The same validation fails in case you use `latest` instead of the `x.x.x` version. 

Example:
`FROM my.private.repo.com:5000/some-image:latest`

**Comment by rcjsuen** [comment]
@lucianenache Thank you for your bug report. Your case is already covered by my fix in rcjsuen/dockerfile-utils#39. I have added your sample to my test suite nonetheless. Have a nice day!

https://github.com/rcjsuen/dockerfile-utils/commit/36b99aedb9ee535b9e78f47ff51e2368d2e2ce0b

**Comment by lucianenache** [comment]
Thanks, for some reason under vscode I still get a warning even with the latest version of the plugin.
![image](https://user-images.githubusercontent.com/2980550/42215105-c15ba102-7ebd-11e8-878b-cd761490d1f1.png)

**Comment by rcjsuen** [comment]
@lucianenache Sorry for the confusion. The issue has been fixed _upstream_ but the vscode-docker extension has not yet been updated to include this fix.

I will comment here when the fix has been adopted so please hang tight!

**Comment by Frodox** [comment]
subscribing for comments - new version released :)

**Comment by rcjsuen** [comment]
The fix has been adopted as you can see in #291. However, a new release of vscode-docker will still need to be cut first.

**Comment by StephenWeatherford** [comment]
@corey-aloia-sap Just wanted to let you know that we have published a new version of the Docker extension that should contain this fix.  Happy coding!
